### ISSUE TITLE
Broken words in documentation tables

### ISSUE THREAD

**Issue by migurski** [mapzen/styleguide#105]
In Safari 9.0.2, https://mapzen.com/documentation/turn-by-turn/api-reference/ looks like:

<img width="729" alt="broken-tables" src="https://cloud.githubusercontent.com/assets/58730/12379306/b7f9976a-bd0c-11e5-8d97-83b15063bb94.png">

**Comment by louh** [comment]
Related, word break issues in blog posts. This seems high enough priority to find a solution for this by end of week.

**Comment by louh** [comment]
After some investigation, this is happening on documentation because we've already consolidated table styles across this and the blog.

The culprit is here: https://github.com/mapzen/styleguide/blob/master/src/stylesheets/common/_tables.scss#L5, which causes the word breaking observed in this issue and also in @IndyHurt's blog post this week.

This was a sledgehammer of a solution to the problem of tables breaking layouts on mobile devices (or smaller-width screens) because there are either too many columns or that there is very long text, the most egregious culprits being when someone writes `a_long_variable_that_exists_in_code_and_must_be_documented_somehow`, or writing a long URL. 

Originally, documentation-repo's table styles attempted to solve the problem with the following strategies:
- By breaking words only in code blocks below a certain breakpoint
- By wrapping tables in a containing `<div>` that would permit x-axis scrolling only for wide tables (rather than the entire page)

Currently, the blog (Jekyll) renders tables from Markdown in its own way, so it's worth exploring if there should be a way to hook into this (via a plugin?) to apply the `<div class='table-wrapper'>`.

Another option is to be much, much smarter about cross-browser compatible word hyphenation. The only way to achieve this is to have some library help us out by putting in hyphenation hints using the `&shy;` soft hyphen. [Some additional information on how this works.](https://css-tricks.com/almanac/properties/h/hyphenate/) Note that browsers do not automatically insert these soft hyphens. We will need to generate them somehow. This can either happen on a per-project basis during the page generating, or client-side after the page has been delivered.

Still need investigating: is there a Jekyll plugin that can do this?
There are also client-side libraries for this, e.g. [Hyphenator.js](http://mnater.github.io/Hyphenator/), or this Node-based [Typeset.js](https://blot.im/typeset/). Client-side libraries are likely to add to the Javascript weight because it has to store a lot of patterns for matching text.

**Comment by louh** [comment]
I just realized how the documentation generator was wrapping the tables. It's just [client side Javascript](https://github.com/mapzen/mapzen-docs-generator/blob/master/theme/js/base.js#L189-L190):

``` js
  // Wrap all tables in a wrapper div
  $('.table').wrap('<div class="table-wrapper"></div>');
```

If we want to, we can do this site-wide now.

**Comment by migurski** [comment]
Would it be better to have the default table style not break, and allow for a specific class to cause it to wrap in certain cases? Also, to have the `wrapper` be a class on the `table` instead of an enclosing `div`?

**Comment by migurski** [comment]
(I mean I think it would be better, but I’m still phrasing this as a question)

**Comment by louh** [comment]
(oh good because I have answers)

So if there's a specific class to enable word breaking / hyphenation, I don't think it's a good experience to ask the table creator to know when / how to use it. Especially if someone writes a table in Markdown for a blog post, like Indy started with. There's no canonical in-universe way to add a custom class.

Ideally, we do want words in the table only break when needed, and that would happen automatically without really needing any intervention from the table creator. We could perhaps attempt to detect certain conditions and then apply the class dynamically.

As to the `wrapper` being on the `table` itself: unfortunately, that's not how tables work. The `wrapper` container is what allows scrolling to occur if the table is wide. The table  cannot permit scrolling within itself. (You can do it if it's `display: block`, but this makes the table not lay out properly -- like columns not expanding to fill the width of the table.)

**Comment by migurski** [comment]
I’m actually comfortable asking an author to need to know that class—the failure mode here is much worse-looking than bumping the page out horizontally, so the default for a naive author should be non-wrapping text, I think.

I understand what you mean about the wrapper, though.
