### ISSUE TITLE
Research possibility of namespaced jQuery/Bootstrap dependencies

### ISSUE THREAD

**Issue by migurski** [mapzen/styleguide#109]
Part of https://github.com/mapzen/styleguide/issues/94, we need to know whether Bootstrap can be asked to use jQuery from someplace other than `window.$`.

**Comment by louh** [comment]
Kinda.

jQuery doesn't care where it is. So it's not it's fault.

Bootstrap does, expecting jQuery to be located at `window.jQuery` actually. So we still have to make that happen.

Here's a proposal:
1. In the bundle, load jQuery (let's call it jQuery B) and expose it globally.
2. if jQuery B detects that another version of jQuery is loaded (let's call it jQuery A), then jQuery A is stashed somewhere, and jQuery B becomes the canonical `$`.
3. Since we explicitly asked for jQuery B, this is the one that we load Bootstrap onto.

Next...
OPTION A.

After loading all the styleguide stuff, we attach jQuery B to a namespaced object `MPZN`. We then call `$.noConflict()`. This restores jQuery A from stash. jQuery A is now canonical `$`, and jQuery B, with Bootstrap attached, can be accessed at `MPZN.$`. By the time the Mapzen Common JS has finished loading, its jQuery (B) has come and gone, and the developer only sees jQuery A, unless they need to go around looking for jQuery B at `MPZN.$`.

OPTION B.

Don't do anything else. jQuery A is still stashed, but it is now up to the developer to restore it with `$.noConflict()`. This means the developer has the flexibility of writing additional code that depends on jQuery B, restoring it to jQuery A for other scripts on their own terms. However, the tradeoff is that unless the developer already knows that Mapzen Common JS is loading its own jQuery and overwriting `$`, then the version of `$` seems to come from a magic place, and the developer must know to call `noConflict` on their own.

---

Another idea.

Something like this where the Bootstrap plugins are re-written in [vanilla Javascript](https://github.com/thednp/bootstrap.native/). Since none of the other parts of Mapzen Common JS requires jQuery (only Bootstrap does) this removes Bootstrap's jQuery dependency entirely, and allows the developer to utilize their own jQuery (or not) at their discretion with no other side effects.

Tradeoffs: this is a third-party library which means support and release schedule may not be as reliable as stock Bootstrap.

**Comment by migurski** [comment]
Huh, that Bootstrap Native concept is super interesting.

How sensitive to load order are the options above? In other words, do they work equally well when some other jQuery is loaded before or after?

**Comment by louh** [comment]
Under Option A, both of these are equivalent:

``` html
  <script src='https://code.jquery.com/jquery-1.12.0.min.js'></script>
  <script src='scripts/mapzen-styleguide.min.js'></script>
```

``` html
  <script src='scripts/mapzen-styleguide.min.js'></script>
  <script src='https://code.jquery.com/jquery-1.12.0.min.js'></script>
```

The effect is that Bootstrap uses its own jQuery but the developer sees their own version of jQuery.

Under Option B, load order does matter. This means jQuery B is canonical unless jQuery A is manually restored:

``` html
  <script src='https://code.jquery.com/jquery-1.12.0.min.js'></script>
  <script src='scripts/mapzen-styleguide.min.js'></script>
```

This means jQuery A overwrites jQuery B:

``` html
  <script src='scripts/mapzen-styleguide.min.js'></script>
  <script src='https://code.jquery.com/jquery-1.12.0.min.js'></script>
```

The other observation I have about Bootstrap Native is that it's pretty recent, and the current 3.3.x branch is pretty stable. We could _probably_ drop it in now and not have to worry too much about breaking changes for a whole year. By the time we want to do something like adopt Bootstrap 4, we will need to be revisiting the entire styleguide anyway.

**Comment by migurski** [comment]
So with Bootstrap Native, we’d skip using jQuery entirely? People could still include it, but it’d be 100% separate? That’s really attractive, if you think that Native is stable enough to use for a year.

**Comment by migurski** [comment]
Option A sounds vastly preferable to B by the way, since it’s independent of load order and leaves the developer with fewer choices.

**Comment by sleepylemur** [comment]
The solution we decided on is to import jquery in noconflct mode which doesn't add it to the global namespace and using browserify-shim to bind bootstrap to our internal jquery. We're exporting the bootstrap-bound jquery at MPZN.$ for internal calling of bootstrap functions.

The pros of this seem to be:
- Simplicity. If somebody wants access to $, then they import jquery. We don't have any surprising import behavior.
- Frees us from providing jquery for the future. If we decide to remove our dependency on jquery in the future through something like bootstrap native, then we can without any fuss.

Cons:
- Sometimes jquery will be double imported.
- Calling Bootstrap javascript is uglier. (This may not really matter if styleguide users aren't exposed to it.)

If we start creating javascript heavy components, we'll have a better idea of what sort of api we want to expose and we may need to revisit this issue.

**Comment by migurski** [comment]
:+1: to this solution. The pros are great, and I like how it insulates the future from the ugliness of the present.
