### ISSUE TITLE
“Copy Failed” when trying to use copy button

### ISSUE THREAD

**Issue by migurski** [mapzen/styleguide#163]
Safari 9.0.2, looks like:

<img width="728" alt="copy" src="https://cloud.githubusercontent.com/assets/58730/12500394/9f9a2596-c067-11e5-8c7a-ffe8c72fde1e.png">

**Comment by hanbyul-here** [comment]
It is expected behavior on Safari, (Safari doesn't support copy/cut functionality of command exec api ). We can say that 'your broswer doesn't support this'.
But! interesting thing is that Safari does support selection, so actually the code snippet is selected, if you press ctr+c after failed, you can see that code is copied into your clipboard. I thought about putting 'press ctr+c to copy' on Safari, but since selected text is not visible, maybe it would confuse people?

**Comment by souperneon** [comment]
We talked about this. I think we will go with @hanbyul-here's suggestion. Once  you user clicks the copt button, showing the message 'Press ⌘ + C' to copy for Safari users in a non-red color.

**Comment by migurski** [comment]
Can we just hide the thing on browsers that don’t support it? People can figure out how to copy/paste a bit of text themselves, I’m sure.
