### ISSUE TITLE
Update data pages styles

### ISSUE THREAD

**Issue by louh** [mapzen/styleguide#209]
After data pages are ported, [these styles](https://github.com/mapzen/data-pages/blob/master/src/templates/index.mustache.html#L13-L46) should be reflected in this [stylesheet](https://github.com/mapzen/styleguide/blob/master/src/stylesheets/common/_data-pages.scss) and removed from the template.

**Comment by hanbyul-here** [comment]
This needs to be in `common`? Wouldn't it be better to separate `data-page` and make it project specific?

**Comment by louh** [comment]
I think this was reflecting earlier styleguide decision of moving ALL front-end styles into styleguide even if it is only used in one place.

No need to do it if this paradigm has shifted.

**Comment by hanbyul-here** [comment]
ah no, our styleguide's paradigm is still same. I think it makes sense to put everything in styleguide repo, to make variable, dependency coherent, but maybe it doesn't need to sit in `common` [directory](https://github.com/mapzen/styleguide/tree/master/src/stylesheets/common), maybe [project specific](https://github.com/mapzen/styleguide/tree/master/src/stylesheets/project_specific) will make more since it got separated from rails app.

**Comment by hanbyul-here** [comment]
so data page is not going to be in styleguide repo so closing it.
