### ISSUE TITLE
Pricing: Add icon assets

### ISSUE THREAD

**Issue by souperneon** [mapzen/styleguide#414]

**Comment by louh** [comment]
OK - these are all the icon assets we will need on the pricing page! I don't know if any of these are already present, so forgive me if I put something down that already exists somewhere. If it does, point me at a url!

- [x] Transparent lightning bolt, on white circle (inverse), transparent background - optimum display size around 48x48 to 60x60
![screenshot 2017-04-11 18 04 16](https://cloud.githubusercontent.com/assets/2553268/24932858/72ad338c-1ee1-11e7-85ac-4256d089a965.png)
- [x] White lightning bolt, on purple circle - optimum display size ~ 24x24
![screenshot 2017-04-11 18 04 08](https://cloud.githubusercontent.com/assets/2553268/24932897/a20ffeb6-1ee1-11e7-8914-4ea7b45f0613.png)
- [x] White map, on purple circle - optimum display size ~ 24x24
![screenshot 2017-04-11 18 04 08](https://cloud.githubusercontent.com/assets/2553268/24932904/a95ed368-1ee1-11e7-9be3-d84f2b7d3442.png)
- [x] White dropped marker, on purple circle - optimum display size ~ 24x24
![screenshot 2017-04-11 18 04 11](https://cloud.githubusercontent.com/assets/2553268/24932971/ef23ed0c-1ee1-11e7-9767-c8bb39a7b0b8.png)
- [x] White checkmark on light purple circle - optimum display size ~ 14x14
![screenshot 2017-04-11 18 04 26](https://cloud.githubusercontent.com/assets/2553268/24932994/0c156b70-1ee2-11e7-8c39-92955a912746.png)
- [x] Dark gray arrow bracket on transparent - optimum display size ~ 16x16
![screenshot 2017-04-11 18 04 48](https://cloud.githubusercontent.com/assets/2553268/24933006/1b11ddca-1ee2-11e7-86ec-bbed643ab8c4.png)

Note: SVGs created already contain margins (e.g. https://mapzen.com/common/styleguide/images/divider/compass-inverse.svg). Was this done for a particular reason? Can we have the SVG viewBox be cropped to fit the icon size exactly? (This allows us to control spacing via CSS exactly instead of estimating what spacing is already inside the SVG.)

**Comment by souperneon** [comment]
[Archive.zip](https://github.com/mapzen/styleguide/files/926531/Archive.zip)
Named the assets for pricing page in the order they are to appear. 
@hanbyul-here is using fontawesome for the checkmark
arrow no longer needed coz no FAQ
