### ISSUE TITLE
Tooltips and popovers: enable via Bootstrap

### ISSUE THREAD

**Issue by louh** [mapzen/styleguide#496]
Consider importing [Bootstrap's tooltips and popovers](https://getbootstrap.com/javascript/#popovers), making them available for admin pages (and potentially other content requiring secondary explanation) - via @sleepylemur and @cedric

**Comment by cedric** [comment]
I have a note to look at adding tool tips on our general backlog:
https://github.com/mapzen/developer/projects/4

I like the idea, but would we really want both? They seem to be pretty similar to me. Either way, it does feel like we're putting copy in call-out boxes all over the place and this approach might help clean-up the interface.

**Comment by louh** [comment]
Tooltips are meant for very short amounts of text and popovers allow for more content. I can definitely see popovers as a useful element for our API key swapping work. See https://github.com/mapzen/documentation/issues/309

**Comment by louh** [comment]
Related: verify if separate tooltip library is still used in developer dashboard - either replace with Bootstrap tooltips, or remove the old library

**Comment by hanbyul-here** [comment]
For Developer Dashboard : `jquery-poshytip` is being included because `jquery-editable`  (plugin we are using to edit the key name inline) is depending on it. Good news is that `jquery-editable` also offers the version based on bootstrap instead of jquery. I will work on styleguide including tooltip and popover, then get rid of jquery poshytip from developer dashboard.

**Comment by louh** [comment]
Closed via https://github.com/mapzen/styleguide/pull/501
