### ISSUE TITLE
Do a complete inventory of Javascript we use on the site

### ISSUE THREAD

**Issue by migurski** [mapzen/styleguide#94]
We’ve copied application.js as a one-time minified blob from the /developers site. Move it from there to here?

**Comment by migurski** [comment]
Example: `samples/documentation.html` has a bunch of live JS links to another domain, so those should probably be brought in as part of this issue.

**Comment by louh** [comment]
What do you mean, another domain? besides mapzen.com ?

**Comment by louh** [comment]
This might be a bit messy, but we can go over this first thing on Monday ?

https://gist.github.com/louh/cf45f95dfab4557ac3b3

The most important part is the list at the bottom, which is probably the most useful shared bundle for JavaScript.

**Comment by louh** [comment]
Additional points that came up today
- @baldur mentioned using [require.js](http://requirejs.org/), which is probably most like what I had assumed we'd do (but I'd use [Browserify](http://browserify.org/), as we have with many other projects). Another suggestion is a JavaScript that only injects a bunch of script tags to load other sources, including jQuery and Bootstrap via CDN, so that we're not bundling things ourselves, but it does kick off a bunch of parallel requests. ([More fun info about how to handle async loading with this method](http://www.html5rocks.com/en/tutorials/speed/script-loading/).)
- @hanbyul-here noted that if use CDN sources, some users who have common libraries (e.g. jQuery) cached will benefit from it. The trade-off is telling developers that they will have to write several script tags for core Mapzen functionality.

**Comment by migurski** [comment]
Great list! Dumb JS question: do the various libraries get minified and _then_ concatenated together?

**Comment by migurski** [comment]
Couple outcomes from today’s conversation:
1. Need to determine our approach to namespace, and decide whether we’re okay pinning a specific version of jQuery and Bootstrap to the global namespace or creating a contained `window.mapzen_styleguide` space for linked libraries. See https://github.com/mapzen/styleguide/issues/109.
2. May need to eventually remove Developer sample page from this repository, since it includes patterns and components that aren’t part of the official styleguide. We want to avoid unnecessary cross-dependencies; things like `/developers` should depend on styleguide and not vice-versa.
